apiVersion: v1
kind: Service
metadata:
  name: nrp-frontend
  labels:
    app: nrp-frontend
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: nrp-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrp-frontend
  template:
    metadata:
      labels:
        app: nrp-frontend
    spec:
      containers:
        - name: nrp-frontend
          image: rifqifatih/nrp_frontend
          imagePullPolicy: Always
          ports:
          - containerPort: 9000