apiVersion: v1
kind: Service
metadata:
  name: nrp-frontend
  labels:
    app: nrp-frontend
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30000
  selector:
    app: nrp-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrp-frontend
  template:
    metadata:
      labels:
        app: nrp-frontend
    spec:
      containers:
        - name: nrp-frontend
          image: rifqifatih/nrp_frontend
          imagePullPolicy: Always
          ports:
          - containerPort: 9000
          volumeMounts:
          - name: nrp-models
            mountPath: /home/bbpnrsoa/nrp/src/Models
          - name: nrp-experiments
            mountPath: /home/bbpnrsoa/nrp/src/Experiments
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nrp
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: init-nrp-models
        image: k8s.gcr.io/git-sync:v3.1.3
        volumeMounts:
        - mountPath: /tmp
          name: nrp-models
        env:
        - name: GIT_SYNC_REPO
          value: https://bitbucket.org/hbpneurorobotics/Models.git
        - name: GIT_SYNC_BRANCH
          value: master18
        - name: GIT_SYNC_ROOT
          value: /tmp
        - name: GIT_SYNC_TIMEOUT
          value: 600
      - name: init-nrp-experiments
        image: k8s.gcr.io/git-sync:v3.1.3
        volumeMounts:
        - mountPath: /tmp
          name: nrp-experiments
        env:
        - name: GIT_SYNC_REPO
          value: https://bitbucket.org/hbpneurorobotics/Experiments.git
        - name: GIT_SYNC_BRANCH
          value: master18
        - name: GIT_SYNC_ROOT
          value: /tmp
        - name: GIT_SYNC_TIMEOUT
          value: 600
      volumes:
      - name: nrp-models
        emptyDir: {}
      - name: nrp-experiments
        emptyDir: {}
      - name: nrp-user-data
        hostPath:
          path: /home/bbpnrsoa/.opt/nrpStorage